image:  yegor256/rultor-image
architect:
  - rocket-3
assets:
  pgSecret.txt: rocket-3/dbgit-test#pgSecret.txt
  gitSecret.txt: rocket-3/dbgit-test#gitSecret.txt
merge:
  script: |-
    pdd -f /dev/null
    java -version --batch-mode
    mvn -version --batch-mode
    mvn clean install -Pqulice --batch-mode -Dstyle.color=never
