name: build

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  lint:
    name: Like Rultor
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Ruby 2.7
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7
      - name: Install pdd
        run: gem install pdd
      - name: JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Puzzles
        run: pdd --file=/dev/null
      - name: Qulice
        run: mvn clean install -Pqulice -DskipTests=true --errors --batch-mode
      - name: Tests
        env:
          pgUser: ${{ secrets.pgUser }}
          pgPass: ${{ secrets.pgPass }}
        run: mvn test -DpgUser="$pgUser" -DpgPass="$pgPass"
